apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jspolicy
spec:
  releaseName: jspolicy
  install:
    createNamespace: true
  targetNamespace: flux-system
  chart:
    spec:
      chart: jspolicy
      sourceRef:
        kind: HelmRepository
        name: jspolicy
        namespace: flux-system
      version: "0.2.0"
  interval: 10m0s
  values:
    replicaCount: 1
    jspolicy:
        limits:
          memory: 1024Mi
          cpu: "2"
        requests:
          memory: 512Mi
          cpu: 500m

